import { writeFileSync, mkdirSync, readFileSync, existsSync, rmSync, rmdirSync, readdirSync, lstatSync, realpathSync, statSync } from 'fs';
import { basename, join } from 'path';
import inquirer from 'inquirer';
import { readTemplate, readUserInvocableSkills } from '../utils/templates.js';
import type { OpenCodeConfig, HarnessAdapter, FileEntry, Provider, OpenCodeProvider, HarnessSection, SharedConfig } from '../types.js';
import { AGENT_NAMES, LEGACY_AGENT_NAME } from '../constants.js';
import { FileWriteError, HarnessConfigError } from '../utils/errors.js';
import { shortPath, getGlobalOpencodeDir, resolveSkillsPath } from '../services/paths.js';
import { OpenCodeConfigSchema } from '../utils/schemas.js';
import { openCodeThinkingOptions, OPENCODE_THINKING_KEYS } from '../utils/thinking.js';
import { promptForOpenCodeProvider, promptForOpenCodeModels, guardProvider } from '../services/prompt.js';

const OPENCODE_PROVIDERS: { name: string; value: OpenCodeProvider }[] = [
  { name: 'OpenCode Zen', value: 'opencode-zen' },
  { name: 'OpenCode Go', value: 'opencode-go' },
  { name: 'Amazon Bedrock', value: 'amazon-bedrock' },
  { name: 'OpenAI', value: 'openai' },
];

const PROVIDER_MODELS: Record<OpenCodeProvider, readonly string[]> = {
  'opencode-zen': [
    'gpt-6-astra', 'gpt-6-sol', 'gpt-6-luna',
    'claude-opus-5-5', 'claude-fable-5-1', 'claude-sonnet-5', 'claude-haiku-4-5',
    'glm-5.3', 'glm-5.3-flash', 'kimi-k3', 'kimi-k2.7-code',
    'deepseek-v4.1-flash', 'deepseek-v4-pro', 'minimax-m3',
    'qwen3.8-max', 'qwen3.8-flash', 'mimo-v2.6-flash-free',
    'gemini-3.8-flash', 'gemini-3.1-pro',
  ].map(id => `opencode/${id}`),
  'opencode-go': [
    'glm-5.3', 'glm-5.3-flash', 'kimi-k3',
    'deepseek-v4.1-flash', 'deepseek-v4-pro', 'minimax-m3',
    'qwen3.8-max', 'qwen3.8-flash', 'mimo-v2.6-pro', 'mimo-v2.6-flash', 'gpt-6-luna',
  ].map(id => `opencode-go/${id}`),
  'amazon-bedrock': [
    'us.anthropic.claude-opus-5-5', 'us.anthropic.claude-fable-5-1',
    'us.anthropic.claude-sonnet-5', 'us.anthropic.claude-haiku-4-5-20251001-v1:0',
  ].map(id => `amazon-bedrock/${id}`),
  openai: ['gpt-6-astra', 'gpt-6-sol', 'gpt-6-luna', 'gpt-5.6-sol', 'gpt-5.6-terra', 'gpt-5.6-luna', 'gpt-5.3-codex-spark'].map(id => `openai/${id}`),
};

const DEFAULT_MODELS: Record<OpenCodeProvider, Record<'build' | 'plan' | typeof AGENT_NAMES[number], string>> = {
  'opencode-zen': {
    sentinel: 'opencode/glm-5.3-flash', oracle: 'opencode/kimi-k3', architect: 'opencode/glm-5.3',
    build: 'opencode/deepseek-v4.1-flash', plan: 'opencode/glm-5.3',
  },
  'opencode-go': {
    sentinel: 'opencode-go/glm-5.3-flash', oracle: 'opencode-go/mimo-v2.6-pro', architect: 'opencode-go/glm-5.3',
    build: 'opencode-go/deepseek-v4.1-flash', plan: 'opencode-go/glm-5.3',
  },
  'amazon-bedrock': {
    sentinel: 'amazon-bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0',
    oracle: 'amazon-bedrock/us.anthropic.claude-fable-5-1',
    architect: 'amazon-bedrock/us.anthropic.claude-opus-5-5',
    build: 'amazon-bedrock/us.anthropic.claude-sonnet-5', plan: 'amazon-bedrock/us.anthropic.claude-opus-5-5',
  },
  openai: {
    sentinel: 'openai/gpt-6-luna', oracle: 'openai/gpt-6-astra', architect: 'openai/gpt-6-astra',
    build: 'openai/gpt-6-sol', plan: 'openai/gpt-6-astra',
  },
};

const COMMAND_MARKER = '<!-- Generated by Atelier -->';

export const opencodeAdapter: HarnessAdapter = {
  name: 'opencode',
  providerChoices: OPENCODE_PROVIDERS,
  configSchema: OpenCodeConfigSchema,
  defaultSection,
  modelsForProvider,
  promptSection,
  installAgents,
  mergeHarnessConfig,
  fileList,
  remove,
};

function defaultSection(provider?: Provider): OpenCodeConfig {
  const selectedProvider = (provider as OpenCodeProvider) || 'opencode-zen';
  const defaults = DEFAULT_MODELS[selectedProvider];
  return {
    provider: selectedProvider,
    build_model: defaults.build,
    plan_model: defaults.plan,
    build_thinking: 'high',
    plan_thinking: selectedProvider === 'openai' ? 'xhigh' : 'high',
    agents: AGENT_NAMES.map(name => ({
      template: name,
      name,
      model: defaults[name],
      thinking: name === 'sentinel' ? (selectedProvider === 'amazon-bedrock' ? 'default' : 'low')
        : name === 'oracle' && selectedProvider === 'opencode-go' ? 'on'
        : name === 'architect' && selectedProvider === 'openai' ? 'xhigh' : 'high',
    })),
  };
}

function modelsForProvider(provider?: Provider): readonly string[] {
  const selectedProvider = (provider as OpenCodeProvider) || 'opencode-zen';
  return [...PROVIDER_MODELS[selectedProvider]];
}

async function promptSection(prompt: typeof inquirer, section: HarnessSection): Promise<HarnessSection> {
  const openCodeSection = section as OpenCodeConfig;
  const provider = guardProvider(
    await promptForOpenCodeProvider(prompt, OPENCODE_PROVIDERS, openCodeSection.provider)
  );
  const models = modelsForProvider(provider);
  return promptForOpenCodeModels(prompt, provider === openCodeSection.provider ? openCodeSection : defaultSection(provider), models, provider);
}

function installAgents(section: HarnessSection, basePath: string, sharedConfig?: SharedConfig): void {
  const config = OpenCodeConfigSchema.parse(section);
  const opencodeRoot = getOpencodeRoot(basePath);
  const agentsDir = join(opencodeRoot, 'agent');

  try {
    mkdirSync(agentsDir, { recursive: true });
  } catch (err) {
    throw new FileWriteError(agentsDir, err instanceof Error ? err.message : String(err));
  }
  rmSync(join(agentsDir, `${LEGACY_AGENT_NAME}.md`), { force: true });

  for (const agent of config.agents) {
    const template = readTemplate(agent.template);
    const options = Object.entries(openCodeThinkingOptions(agent.model, agent.thinking)).map(([key, value]) => `${key}: ${JSON.stringify(value)}\n`).join('');
    const frontmatter = `---\nname: ${agent.name}\ndescription: ${template.description}\nmode: subagent\nmodel: ${JSON.stringify(agent.model)}\n${options}---\n`;
    const content = frontmatter + template.body;

    const agentPath = join(agentsDir, `${agent.name}.md`);
    writeFileSync(agentPath, content);
    console.log(`Created ${shortPath(agentPath)}`);
  }

  if (sharedConfig) {
    installCommands(opencodeRoot, sharedConfig);
  }
}

function installCommands(opencodeRoot: string, sharedConfig: SharedConfig): void {
  const discovery = readUserInvocableSkills(resolveSkillsPath(sharedConfig.skills_path));
  reportSkillWarnings(discovery.warnings);
  const commandsDir = getCommandsDir(opencodeRoot, discovery.skills.length > 0);
  if (!commandsDir) {
    return;
  }

  const desiredCommands = new Map(discovery.skills.map(skill => [skill.name, skill]));
  for (const path of managedCommandPaths(commandsDir)) {
    if (!desiredCommands.has(basename(path, '.md'))) {
      rmSync(path, { force: true });
      console.log(`Removed ${shortPath(path)}`);
    }
  }

  for (const skill of discovery.skills) {
    const commandPath = join(commandsDir, `${skill.name}.md`);
    if (commandStatus(commandPath) === 'custom') {
      console.log(`Skipped ${shortPath(commandPath)} because it is not managed by Atelier.`);
      continue;
    }
    const content = `---\ndescription: ${JSON.stringify(skill.description)}\n---\n${COMMAND_MARKER}\nActivate the ${skill.name} skill and follow its instructions precisely.\n\nUser request: $ARGUMENTS\n`;
    writeFileSync(commandPath, content);
    console.log(`Created ${shortPath(commandPath)}`);
  }
}

function mergeHarnessConfig(section: HarnessSection, basePath: string): void {
  const config = OpenCodeConfigSchema.parse(section);
  const opencodeJsonPath = join(basePath, 'opencode.json');
  const existing = readExistingOpenCodeJson(opencodeJsonPath);
  const isNew = Object.keys(existing).length === 0;

  try {
    mkdirSync(basePath, { recursive: true });
  } catch (err) {
    throw new FileWriteError(basePath, err instanceof Error ? err.message : String(err));
  }

  const sentinel = config.agents.find(a => a.name === 'sentinel');
  const architect = config.agents.find(a => a.name === 'architect');

  // Explicit thinking selections replace stale settings from the previous model.
  const existingAgents = existing.agent as Record<string, Record<string, unknown>> | undefined;
  for (const mode of ['build', 'plan'] as const) {
    if (config[`${mode}_thinking`] === undefined || !existingAgents?.[mode]) continue;
    for (const key of OPENCODE_THINKING_KEYS) delete existingAgents[mode][key];
  }

  const atelierFields: Record<string, unknown> = {
    agent: {
      build: {
        mode: 'primary',
        model: config.build_model || sentinel?.model || DEFAULT_MODELS[config.provider].build,
        ...openCodeThinkingOptions(config.build_model, config.build_thinking),
      },
      plan: {
        mode: 'primary',
        model: config.plan_model || architect?.model || DEFAULT_MODELS[config.provider].plan,
        ...openCodeThinkingOptions(config.plan_model, config.plan_thinking),
      },
    },
  };

  if (config.provider === 'amazon-bedrock') {
    atelierFields.provider = {
      'amazon-bedrock': {
        options: {
          region: 'us-east-1',
        },
      },
    };
  }

  const merged = deepMerge(existing, atelierFields);

  try {
    writeFileSync(opencodeJsonPath, JSON.stringify(merged, null, 2) + '\n');
  } catch (err) {
    throw new FileWriteError(opencodeJsonPath, err instanceof Error ? err.message : String(err));
  }
  console.log(`${isNew ? 'Created' : 'Updated'} ${shortPath(opencodeJsonPath)}`);
}

function fileList(basePath: string, sharedConfig?: SharedConfig): FileEntry[] {
  const files: FileEntry[] = [
    { path: join(basePath, 'opencode.json'), exists: existsSync(join(basePath, 'opencode.json')) },
  ];
  const opencodeRoot = getOpencodeRoot(basePath);
  for (const name of AGENT_NAMES) {
    const path = join(opencodeRoot, 'agent', `${name}.md`);
    files.push({ path, exists: existsSync(path) });
  }
  if (sharedConfig) {
    const discovery = readUserInvocableSkills(resolveSkillsPath(sharedConfig.skills_path));
    reportSkillWarnings(discovery.warnings);
    const commandsDir = getCommandsDir(opencodeRoot, discovery.skills.length > 0);
    if (!commandsDir) {
      return files;
    }
    const desiredNames = new Set(discovery.skills.map(skill => skill.name));
    for (const path of managedCommandPaths(commandsDir)) {
      if (!desiredNames.has(basename(path, '.md'))) {
        files.push({ path, exists: true, action: 'delete' });
      }
    }
    for (const skill of discovery.skills) {
      const path = join(opencodeRoot, 'command', `${skill.name}.md`);
      const commandPath = join(commandsDir, `${skill.name}.md`);
      if (commandStatus(commandPath) !== 'custom') {
        files.push({ path, exists: existsSync(commandPath) });
      }
    }
  }
  return files;
}

function remove(section: HarnessSection, basePath: string): void {
  const config = section as OpenCodeConfig;
  const opencodeRoot = getOpencodeRoot(basePath);

  removeAgentFiles(opencodeRoot, config);
  removeLegacyFiles(opencodeRoot);
  writeOrDeleteOpenCodeJson(basePath, config);
}

function removeAgentFiles(opencodeRoot: string, config: OpenCodeConfig): void {
  const agentsDir = join(opencodeRoot, 'agent');

  for (const agent of config.agents) {
    const file = join(agentsDir, `${agent.name}.md`);
    if (existsSync(file)) {
      rmSync(file, { force: true });
    }
  }
  rmSync(join(agentsDir, `${LEGACY_AGENT_NAME}.md`), { force: true });

  removeDirIfEmpty(agentsDir);
}

function removeDirIfEmpty(dir: string): void {
  if (!existsSync(dir)) {
    return;
  }
  try {
    if (readdirSync(dir).length === 0) {
      rmdirSync(dir);
    }
  } catch (err) {
    throw new FileWriteError(dir, err instanceof Error ? err.message : String(err));
  }
}

function removeLegacyFiles(opencodeRoot: string): void {
  const pluginPath = join(opencodeRoot, 'plugins', 'atelier.js');
  if (existsSync(pluginPath)) {
    rmSync(pluginPath, { force: true });
  }

  const commandsDir = getCommandsDir(opencodeRoot, false);
  if (!commandsDir) {
    return;
  }
  for (const path of managedCommandPaths(commandsDir)) {
    rmSync(path, { force: true });
  }
  if (!lstatSync(join(opencodeRoot, 'command')).isSymbolicLink()) {
    removeDirIfEmpty(commandsDir);
  }
}

function reportSkillWarnings(warnings: string[]): void {
  for (const warning of warnings) {
    console.warn(warning);
  }
}

function getCommandsDir(opencodeRoot: string, create: boolean): string | undefined {
  const commandsDir = join(opencodeRoot, 'command');
  if (!existsSync(commandsDir)) {
    if (!create) {
      return undefined;
    }
    try {
      mkdirSync(commandsDir, { recursive: true });
      return commandsDir;
    } catch (err) {
      throw new FileWriteError(commandsDir, err instanceof Error ? err.message : String(err));
    }
  }

  try {
    const stat = lstatSync(commandsDir);
    if (stat.isSymbolicLink()) {
      const target = realpathSync(commandsDir);
      if (!statSync(target).isDirectory()) {
        throw new Error('symbolic link target is not a directory');
      }
      return target;
    }
    if (!stat.isDirectory()) {
      throw new Error('path is not a directory');
    }
    return commandsDir;
  } catch (err) {
    throw new FileWriteError(commandsDir, err instanceof Error ? err.message : String(err));
  }
}

function managedCommandPaths(commandsDir: string): string[] {
  try {
    return readdirSync(commandsDir, { withFileTypes: true })
      .filter(entry => entry.isFile() && entry.name.endsWith('.md'))
      .map(entry => join(commandsDir, entry.name))
      .filter(path => readFileSync(path, 'utf-8').includes(COMMAND_MARKER));
  } catch (err) {
    throw new FileWriteError(commandsDir, err instanceof Error ? err.message : String(err));
  }
}

function commandStatus(path: string): 'missing' | 'managed' | 'custom' {
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink() || !stat.isFile()) {
      throw new Error('command path must be a regular file');
    }
    return readFileSync(path, 'utf-8').includes(COMMAND_MARKER) ? 'managed' : 'custom';
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return 'missing';
    }
    throw new FileWriteError(path, err instanceof Error ? err.message : String(err));
  }
}

function writeOrDeleteOpenCodeJson(basePath: string, config: OpenCodeConfig): void {
  const opencodeJsonPath = join(basePath, 'opencode.json');
  if (!existsSync(opencodeJsonPath)) {
    return;
  }

  const content = stripOpenCodeConfig(
    readExistingOpenCodeJson(opencodeJsonPath),
    config.provider,
  );

  try {
    if (Object.keys(content).length === 0) {
      rmSync(opencodeJsonPath, { force: true });
    } else {
      writeFileSync(opencodeJsonPath, JSON.stringify(content, null, 2) + '\n');
    }
  } catch (err) {
    throw new FileWriteError(opencodeJsonPath, err instanceof Error ? err.message : String(err));
  }
}

function readExistingOpenCodeJson(opencodeJsonPath: string): Record<string, unknown> {
  if (!existsSync(opencodeJsonPath)) {
    return {};
  }
  try {
    const content = readFileSync(opencodeJsonPath, 'utf-8');
    return JSON.parse(content) as Record<string, unknown>;
  } catch (err) {
    throw new HarnessConfigError(opencodeJsonPath, err instanceof Error ? err.message : String(err));
  }
}

function stripOpenCodeConfig(content: Record<string, unknown>, provider: OpenCodeProvider): Record<string, unknown> {
  if (content.agent && typeof content.agent === 'object' && !Array.isArray(content.agent)) {
    const agent = content.agent as Record<string, unknown>;
    for (const mode of ['build', 'plan']) {
      const entry = agent[mode];
      if (!entry || typeof entry !== 'object' || Array.isArray(entry)) continue;
      for (const key of ['mode', 'model', ...OPENCODE_THINKING_KEYS]) delete (entry as Record<string, unknown>)[key];
      if (!Object.keys(entry).length) delete agent[mode];
    }
    if (Object.keys(agent).length === 0) {
      delete content.agent;
    }
  }

  if (provider === 'amazon-bedrock' && content.provider && typeof content.provider === 'object' && !Array.isArray(content.provider)) {
    const providerRecord = content.provider as Record<string, unknown>;
    const bedrock = providerRecord['amazon-bedrock'] as Record<string, unknown> | undefined;
    const options = bedrock?.options as Record<string, unknown> | undefined;
    if (options) {
      delete options.region;
      if (!Object.keys(options).length) delete bedrock!.options;
    }
    if (bedrock && !Object.keys(bedrock).length) delete providerRecord['amazon-bedrock'];
    if (Object.keys(providerRecord).length === 0) {
      delete content.provider;
    }
  }

  return content;
}

export function getOpencodeRoot(basePath: string): string {
  return basePath === getGlobalOpencodeDir() ? basePath : join(basePath, '.opencode');
}

function deepMerge(target: Record<string, unknown>, source: Record<string, unknown>): Record<string, unknown> {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    if (
      typeof source[key] === 'object' &&
      source[key] !== null &&
      !Array.isArray(source[key])
    ) {
      result[key] = deepMerge(
        (result[key] as Record<string, unknown>) || {},
        source[key] as Record<string, unknown>
      );
    } else {
      result[key] = source[key];
    }
  }
  return result;
}
